import { randomUUID } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import { ensureSchema, pool } from "@/lib/db";
import { searchCatalog } from "@/lib/catalog";
import { generateSalaarReply, WHATSAPP_FALLBACK } from "@/lib/salaar";
import {knowledgeAnswer,needsHuman,wantsResellerSignup} from "@/lib/knowledge";

const SESSION_COOKIE="primehub_session";
async function ensureConversation(request:NextRequest){await ensureSchema();let sessionId=request.cookies.get(SESSION_COOKIE)?.value;let createdCookie=false;if(!sessionId){sessionId=randomUUID();createdCookie=true;}let row=(await pool.query("SELECT id FROM conversations WHERE session_id=$1",[sessionId])).rows[0];if(!row){await pool.query("INSERT INTO sessions(id) VALUES($1) ON CONFLICT(id) DO UPDATE SET last_seen_at=NOW()",[sessionId]);const conversationId=randomUUID();row=(await pool.query("INSERT INTO conversations(id,session_id) VALUES($1,$2) ON CONFLICT(session_id) DO UPDATE SET updated_at=NOW() RETURNING id",[conversationId,sessionId])).rows[0];}else{await pool.query("UPDATE sessions SET last_seen_at=NOW() WHERE id=$1",[sessionId]);}return{sessionId,conversationId:row.id as string,createdCookie};}
function withCookie(response:NextResponse,sessionId:string,shouldSet:boolean){if(shouldSet)response.cookies.set(SESSION_COOKIE,sessionId,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",maxAge:31536000});return response;}
async function latestNotes(){return String((await pool.query("SELECT body FROM admin_notes WHERE id=1")).rows[0]?.body||"");}
async function insertSalaar(conversationId:string,text:string,meta:Record<string,unknown>={}){await pool.query("INSERT INTO messages(conversation_id,role,body,meta) VALUES($1,'salaar-stub',$2,$3::jsonb)",[conversationId,text,JSON.stringify(meta)]);}

async function maybeResume(conversationId:string){const c=(await pool.query("SELECT status,hold_until,hard_mute,shown_product_ids FROM conversations WHERE id=$1",[conversationId])).rows[0];if(!c||c.status!=="WAIT"||c.hard_mute||!c.hold_until||new Date(c.hold_until)>new Date())return;const pending=(await pool.query(`SELECT m.id,m.body FROM messages m WHERE m.conversation_id=$1 AND m.role='customer' AND NOT EXISTS(SELECT 1 FROM messages newer WHERE newer.conversation_id=m.conversation_id AND newer.id>m.id AND newer.role='salaar-stub') ORDER BY m.id DESC LIMIT 1`,[conversationId])).rows[0];await pool.query("UPDATE conversations SET status='AUTO',hold_until=NULL WHERE id=$1",[conversationId]);if(!pending)return;const notes=await latestNotes();const known=knowledgeAnswer(pending.body,notes);if(known){await insertSalaar(conversationId,known.text,{link:known.link});return;}const products=searchCatalog(pending.body,c.shown_product_ids||[],3);const reply=await generateSalaarReply(pending.body,products,notes);await insertSalaar(conversationId,reply.text,{products});if(products.length)await pool.query("UPDATE conversations SET shown_product_ids=array_cat(shown_product_ids,$2::text[]),updated_at=NOW() WHERE id=$1",[conversationId,products.map(p=>p.id)]);}

export async function GET(request:NextRequest){try{const{sessionId,conversationId,createdCookie}=await ensureConversation(request);await maybeResume(conversationId);const result=await pool.query("SELECT id,role,body,meta,created_at FROM messages WHERE conversation_id=$1 ORDER BY id ASC",[conversationId]);const cart=(await pool.query("SELECT cart,status,need_you FROM conversations WHERE id=$1",[conversationId])).rows[0];return withCookie(NextResponse.json({conversationId,messages:result.rows,cart:cart?.cart||[],status:cart?.status||'AUTO',needYou:Boolean(cart?.need_you)}),sessionId,createdCookie);}catch(e){console.error(e);return NextResponse.json({error:"Chat is temporarily unavailable"},{status:500});}}

export async function POST(request:NextRequest){try{const payload=await request.json();const body=typeof payload?.body==="string"?payload.body.trim():"";if(!body||body.length>2000)return NextResponse.json({error:"Message must be 1-2000 characters"},{status:400});const{sessionId,conversationId,createdCookie}=await ensureConversation(request);await pool.query("INSERT INTO messages(conversation_id,role,body) VALUES($1,'customer',$2)",[conversationId,body]);await pool.query("UPDATE conversations SET updated_at=NOW() WHERE id=$1",[conversationId]);const c=(await pool.query("SELECT status,hold_until,hard_mute,shown_product_ids FROM conversations WHERE id=$1",[conversationId])).rows[0];const waiting=c?.status==="WAIT"&&(c.hard_mute||!c.hold_until||new Date(c.hold_until)>new Date());
 if(!waiting){if(c?.status==="WAIT")await pool.query("UPDATE conversations SET status='AUTO',hold_until=NULL WHERE id=$1",[conversationId]);const human=needsHuman(body);if(human){await pool.query("UPDATE conversations SET need_you=TRUE,updated_at=NOW() WHERE id=$1",[conversationId]);await insertSalaar(conversationId,`Ji, team ko bula raha hoon. ${WHATSAPP_FALLBACK}`,{needYou:true});}
 else if(wantsResellerSignup(body)){await insertSalaar(conversationId,"Bilkul. Name, email aur phone bhej dein — team approval ke baad reseller account activate hoga.",{resellerSignup:true});}
 else{const notes=await latestNotes();const known=knowledgeAnswer(body,notes);if(known)await insertSalaar(conversationId,known.text,{link:known.link});else{const products=searchCatalog(body,c?.shown_product_ids||[],3);const reply=await generateSalaarReply(body,products,notes);await insertSalaar(conversationId,reply.text,{products});if(products.length)await pool.query("UPDATE conversations SET shown_product_ids=array_cat(shown_product_ids,$2::text[]),updated_at=NOW() WHERE id=$1",[conversationId,products.map(p=>p.id)]);}}
 }
 return withCookie(NextResponse.json({ok:true,waiting}),sessionId,createdCookie);}catch(e){console.error(e);return NextResponse.json({error:"Message could not be saved"},{status:500});}}
