import { randomUUID } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import { ensureSchema, pool } from "@/lib/db";
const SESSION_COOKIE="primehub_session";
const STUB="Salaar yahan se Phase 2 mein baat kare ga. Abhi aapka msg save ho gaya.";
async function ensureConversation(request:NextRequest){await ensureSchema();let sessionId=request.cookies.get(SESSION_COOKIE)?.value;let createdCookie=false;if(!sessionId){sessionId=randomUUID();createdCookie=true;}let row=(await pool.query("SELECT id FROM conversations WHERE session_id=$1",[sessionId])).rows[0];if(!row){await pool.query("INSERT INTO sessions(id) VALUES($1) ON CONFLICT(id) DO UPDATE SET last_seen_at=NOW()",[sessionId]);const conversationId=randomUUID();row=(await pool.query("INSERT INTO conversations(id,session_id) VALUES($1,$2) ON CONFLICT(session_id) DO UPDATE SET updated_at=NOW() RETURNING id",[conversationId,sessionId])).rows[0];}else{await pool.query("UPDATE sessions SET last_seen_at=NOW() WHERE id=$1",[sessionId]);}return{sessionId,conversationId:row.id as string,createdCookie};}
function withCookie(response:NextResponse,sessionId:string,shouldSet:boolean){if(shouldSet)response.cookies.set(SESSION_COOKIE,sessionId,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",maxAge:31536000});return response;}
export async function GET(request:NextRequest){try{const{sessionId,conversationId,createdCookie}=await ensureConversation(request);const result=await pool.query("SELECT id,role,body,created_at FROM messages WHERE conversation_id=$1 ORDER BY id ASC",[conversationId]);return withCookie(NextResponse.json({conversationId,messages:result.rows}),sessionId,createdCookie);}catch(e){console.error(e);return NextResponse.json({error:"Chat is temporarily unavailable"},{status:500});}}
export async function POST(request:NextRequest){try{const payload=await request.json();const body=typeof payload?.body==="string"?payload.body.trim():"";if(!body||body.length>2000)return NextResponse.json({error:"Message must be 1-2000 characters"},{status:400});const{sessionId,conversationId,createdCookie}=await ensureConversation(request);const client=await pool.connect();try{await client.query("BEGIN");await client.query("INSERT INTO messages(conversation_id,role,body) VALUES($1,'customer',$2)",[conversationId,body]);await client.query("INSERT INTO messages(conversation_id,role,body) VALUES($1,'salaar-stub',$2)",[conversationId,STUB]);await client.query("UPDATE conversations SET updated_at=NOW() WHERE id=$1",[conversationId]);await client.query("COMMIT");}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}return withCookie(NextResponse.json({ok:true}),sessionId,createdCookie);}catch(e){console.error(e);return NextResponse.json({error:"Message could not be saved"},{status:500});}}
